name: Build and Release Game

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag version'
        required: true
        default: 'v1.0.0'
      release_options:
        type: object
        properties:
          upload_releases:
            type: boolean
            default: true
            description: 'Upload to GitHub releases'
          mark_prerelease:
            type: boolean
            default: false
            description: 'Mark as pre-release'
          upload_to_itch:
            type: boolean
            default: false
            description: 'Upload to itch.io'

# Reusable configuration
env:
  ITCH_GAME_PATH: 'ragebreaker/just-keep-chasing'
  BUILD_OUTPUT_DIR: '${{ github.workspace }}/builds'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    strategy:
      matrix:
        # Define platforms as a reusable list
        platform:
          - 'Windows Desktop'
          - 'Linux/X11'
          - 'Linux/X11 arm64'
          - 'macOS'
          - 'Android'
          - 'Android x86 and x86 64'
          - 'Web'
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build game for ${{ matrix.platform }}
        uses: mlm-games/godot-build-action@main
        with:
          GODOT_PREVIEW_BUILDS: true
          EXPORT_PRESET_NAME: ${{ matrix.platform }}
          ITCH_USER_SLASH_GAME: ${{ env.ITCH_GAME_PATH }}
          BUTLER_UPLOAD: ${{ inputs.release_options.upload_to_itch || false }}
          # Sensitive data
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Set artifact name
        id: artifact-name
        shell: bash
        run: |
          PLATFORM="${{ matrix.platform }}"
          SAFE_NAME="${PLATFORM//[^a-zA-Z0-9_]/_}"
          echo "name=${SAFE_NAME}" >> $GITHUB_OUTPUT

          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: ${{ env.BUILD_OUTPUT_DIR }}

      - name: Create GitHub release
        if: |
          github.event_name == 'workflow_dispatch' && 
          inputs.release_options.upload_releases
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BUILD_OUTPUT_DIR }}/*
          name: ${{ inputs.tag_name }}
          tag_name: ${{ inputs.tag_name }}
          prerelease: ${{ inputs.release_options.mark_prerelease }}
          generate_release_notes: true
          body: |
            ## Release Notes
            Please check the commit history for detailed changes.
            
            Full changelog will be available soon.